using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MineDefine.Parser.AST
{
    public enum Material
    {
        Air = 00,
        Stone = 01,
        Grass = 02,
        Dirt = 03,
        Cobblestone = 04,
        WoodenPlank = 05,
        Bedrock = 07,
        Water = 08,
        Lava = 10,
        Sand = 12,
        Gravel = 13,
        GoldOre = 14,
        IronOre = 15,
        CoalOre = 16,
        Wood = 17,
        Leaves = 18,
        LapisLazuliOre = 21,
        Dispenser = 23,
        Sandstone = 24,
        StickyPiston = 29,
        Cobweb = 30,
        GrassPlant = 31,
        DeadBush = 32,
        Wool = 35,
        Dandelion = 37,
        Poppy = 38,
        BrownMushroom = 39,
        RedMushroom = 40,
        Slab = 44,
        TnT = 46,
        Bookshelf = 47,
        MossSonte = 48,
        Obsidian = 49,
        Torch = 50,
        Fire = 51,
        MonsterSpawner = 52,
        WoodenStairs = 53,
        Chest = 54,
        RedstoneWire = 55,
        DiamondOre = 56,
        CraftingTable = 58,
        Wheat = 59,
        Farmland = 60,
        Furnace = 61,
        WoodenDoor = 64,
        Ladders = 65,
        Rails = 66,
        StoneStairs = 67,
        Lever = 69,
        StonePressurePlate = 70,
        IronDoor = 71,
        WoodenPressurePlate=72,
        RedstoneOre = 73,
        Button = 77,
        SnowCover = 78,
        Ice = 79,
        Snow = 80,
        Cactus = 81,
        ClayBlock = 82,
        SugarCane = 83,
        Fence = 85,
        Pumpkin = 86,
        Netherrack = 87,
        SoulSand = 88,
        Glowstone = 89,
        Portal = 90,
        RedstoneRepeater = 93,
        MonsterEgg = 97,
        StoneBricks = 98,
        HugeBrownMushroom = 99,
        HugeRedMushroom=100,
        IronBars = 101,
        GlassPane = 102,
        Melon = 103,
        Vines = 106,
        Mycelium = 110,
        LiyPad = 111,
        NetherBrick = 112,
        NetherBrickFence = 113,
        NetherBrickStairs = 114,
        NetherWart=115,
        Cauldron = 118,
        EndPortal = 119,
        EndPortalBlock=120,
        EndStone = 121,
        DragonEgg = 122,
        Cocoa=127,
        SandstoneStairs = 128,
        EmeraldOre = 129,
        TripwireHook = 131,
        Tripwire = 132,
        FlowerPot = 140,
        Carrots = 141,
        Potatoes = 142,
        NetherQuartzOre = 153,
        PackedIce = 174
    }
}
